.TH "DF" "1" "2014\-02\-02" "manpages\-tldr manuals" ""
.SH NAME
.PP
df \- gives an overview of the file system disk space usage
.SH EXAMPLES
.PP
Display all file systems and their disk usage.
.IP
.nf
\f[C]
df
\f[]
.fi
.PP
Display all file systems and their disk usage in human readable form.
.IP
.nf
\f[C]
df\ \-h
\f[]
.fi
.SH AUTHORS
Shrayas Rajagopal, Boris Egorov.
