.TH "KILL" "1" "2014\-02\-02" "manpages\-tldr manuals" ""
.SH NAME
.PP
kill \- Sends a signal to a process.
Mostly used for stopping processes.
.SH EXAMPLES
.PP
Kill the process.
.IP
.nf
\f[C]
kill\ process_id
\f[]
.fi
.PP
List signal names.
.IP
.nf
\f[C]
kill\ \-l
\f[]
.fi
.SH AUTHORS
Zlatan Vasović, Boris Egorov.
