.TH "WC" "1" "2014\-02\-02" "manpages\-tldr manuals" ""
.SH NAME
.PP
wc \- Count words, bytes, or lines
.SH EXAMPLES
.PP
Count lines in file.
.IP
.nf
\f[C]
wc\ \-l\ file
\f[]
.fi
.PP
Count bytes in file.
.IP
.nf
\f[C]
wc\ \-c\ file
\f[]
.fi
.PP
Count characters in file (taking multi\-byte character sets into
account).
.IP
.nf
\f[C]
wc\ \-m\ file
\f[]
.fi
.SH AUTHORS
Pranav Raja, Boris Egorov.
